version: '3'
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    restart: always

  api:
    build:
      context: .
    container_name: file-mapper-api
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
    depends_on:
      - db
